
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bottlesite_container
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    volumes:
      - ./:/app
    networks:
      - bottle_postgres_network
  
  postgres:
    image: postgres:latest
    container_name: bottlesite_postgres_container
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
      - "5432:5432"

    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    networks:
      - bottle_postgres_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python
    networks:
      - bottle_postgres_network

networks:
  bottle_postgres_network:
